baseUrlSport=https://sport-reservation-2-api-bootcamp.do.dibimbing.id/api/v1
baseUrlResonance=https://resonance.dibimbing.id
baseUrl=https://sport-reservation-2-api-bootcamp.do.dibimbing.id/api/v1
emailSport=syukran@gmail.com
passwordSport=syukran123
usernameOrEmailResonance=user1
passwordResonance=password
